// <auto-generated />
using System;
using MaggiesPlaygroundApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaggiesPlaygroundApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250624170113_AddPhonesAndPhoneTypes")]
    partial class AddPhonesAndPhoneTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressTypeId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.AddressType", b =>
                {
                    b.Property<int>("AddressTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressTypeId"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<bool>("ClientOption")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("AddressTypeId");

                    b.ToTable("AddressTypes");

                    b.HasData(
                        new
                        {
                            AddressTypeId = 1,
                            ClientOption = false,
                            Description = "Home address",
                            Name = "Home"
                        },
                        new
                        {
                            AddressTypeId = 2,
                            ClientOption = false,
                            Description = "Work address",
                            Name = "Work"
                        },
                        new
                        {
                            AddressTypeId = 3,
                            ClientOption = false,
                            Description = "Billing address",
                            Name = "Billing"
                        },
                        new
                        {
                            AddressTypeId = 4,
                            ClientOption = false,
                            Description = "Shipping address",
                            Name = "Shipping"
                        },
                        new
                        {
                            AddressTypeId = 5,
                            ClientOption = false,
                            Description = "Mailing address",
                            Name = "Mailing"
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("ClientTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientTypeId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Active = true,
                            ClientName = "Acme Corporation",
                            ClientTypeId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Active = true,
                            ClientName = "TechStart Inc",
                            ClientTypeId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Active = true,
                            ClientName = "Local Bakery",
                            ClientTypeId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Active = true,
                            ClientName = "City Health Department",
                            ClientTypeId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Active = true,
                            ClientName = "Green Earth Foundation",
                            ClientTypeId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Active = true,
                            ClientName = "Global Industries",
                            ClientTypeId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Active = true,
                            ClientName = "Innovate Labs",
                            ClientTypeId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Active = true,
                            ClientName = "Family Restaurant",
                            ClientTypeId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Active = true,
                            ClientName = "County Education Board",
                            ClientTypeId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Active = true,
                            ClientName = "Community Outreach",
                            ClientTypeId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Active = true,
                            ClientName = "MegaCorp International",
                            ClientTypeId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Active = true,
                            ClientName = "Future Tech",
                            ClientTypeId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Active = true,
                            ClientName = "Neighborhood Cafe",
                            ClientTypeId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Active = true,
                            ClientName = "State Transportation",
                            ClientTypeId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Active = true,
                            ClientName = "Youth Development",
                            ClientTypeId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Active = true,
                            ClientName = "Enterprise Solutions",
                            ClientTypeId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Active = true,
                            ClientName = "NextGen Innovations",
                            ClientTypeId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Active = true,
                            ClientName = "Artisan Crafts",
                            ClientTypeId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Active = true,
                            ClientName = "Public Safety",
                            ClientTypeId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        },
                        new
                        {
                            ClientId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Active = true,
                            ClientName = "Cultural Heritage",
                            ClientTypeId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System"
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.ClientType", b =>
                {
                    b.Property<int>("ClientTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientTypeId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("ClientTypeId");

                    b.ToTable("ClientTypes");

                    b.HasData(
                        new
                        {
                            ClientTypeId = 1,
                            Active = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            Name = "Corporate"
                        },
                        new
                        {
                            ClientTypeId = 2,
                            Active = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            Name = "Small Business"
                        },
                        new
                        {
                            ClientTypeId = 3,
                            Active = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            Name = "Startup"
                        },
                        new
                        {
                            ClientTypeId = 4,
                            Active = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            Name = "Non-Profit"
                        },
                        new
                        {
                            ClientTypeId = 5,
                            Active = true,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            Name = "Government"
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenderId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Male",
                            EnteredBy = "System",
                            Name = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Female",
                            EnteredBy = "System",
                            Name = "Female"
                        },
                        new
                        {
                            GenderId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Other/Unspecified",
                            EnteredBy = "System",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("PersonTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Suffix")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("PersonId");

                    b.HasIndex("GenderId");

                    b.HasIndex("PersonTypeId");

                    b.HasIndex("RaceId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Alias = "jsmith",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "John",
                            GenderId = 1,
                            LastName = "Smith",
                            MiddleName = "A",
                            PersonTypeId = 1,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Alias = "ejohnson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Emily",
                            GenderId = 2,
                            LastName = "Johnson",
                            MiddleName = "B",
                            PersonTypeId = 2,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Alias = "mwilliams",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1978, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Michael",
                            GenderId = 1,
                            LastName = "Williams",
                            MiddleName = "C",
                            PersonTypeId = 3,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Alias = "sbrown",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Sarah",
                            GenderId = 2,
                            LastName = "Brown",
                            MiddleName = "D",
                            PersonTypeId = 4,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Alias = "djones",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1980, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "David",
                            GenderId = 1,
                            LastName = "Jones",
                            MiddleName = "E",
                            PersonTypeId = 1,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Alias = "jgarcia",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Jessica",
                            GenderId = 2,
                            LastName = "Garcia",
                            MiddleName = "F",
                            PersonTypeId = 2,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Alias = "cmiller",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Chris",
                            GenderId = 1,
                            LastName = "Miller",
                            MiddleName = "G",
                            PersonTypeId = 3,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Alias = "adavis",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Ashley",
                            GenderId = 2,
                            LastName = "Davis",
                            MiddleName = "H",
                            PersonTypeId = 4,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Alias = "mmartinez",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1983, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Matthew",
                            GenderId = 1,
                            LastName = "Martinez",
                            MiddleName = "I",
                            PersonTypeId = 1,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Alias = "ahernandez",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Amanda",
                            GenderId = 2,
                            LastName = "Hernandez",
                            MiddleName = "J",
                            PersonTypeId = 2,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Alias = "jlopez",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1987, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Joshua",
                            GenderId = 1,
                            LastName = "Lopez",
                            MiddleName = "K",
                            PersonTypeId = 3,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Alias = "bgonzalez",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1996, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Brittany",
                            GenderId = 2,
                            LastName = "Gonzalez",
                            MiddleName = "L",
                            PersonTypeId = 4,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Alias = "rwilson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1982, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Robert",
                            GenderId = 1,
                            LastName = "Wilson",
                            MiddleName = "M",
                            PersonTypeId = 1,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Alias = "janderson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Jennifer",
                            GenderId = 2,
                            LastName = "Anderson",
                            MiddleName = "N",
                            PersonTypeId = 2,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Alias = "dthomas",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1979, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Daniel",
                            GenderId = 1,
                            LastName = "Thomas",
                            MiddleName = "O",
                            PersonTypeId = 3,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000016"),
                            Alias = "ltaylor",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Lisa",
                            GenderId = 2,
                            LastName = "Taylor",
                            MiddleName = "P",
                            PersonTypeId = 4,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000017"),
                            Alias = "jmoore",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "James",
                            GenderId = 1,
                            LastName = "Moore",
                            MiddleName = "Q",
                            PersonTypeId = 1,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000018"),
                            Alias = "mjackson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Michelle",
                            GenderId = 2,
                            LastName = "Jackson",
                            MiddleName = "R",
                            PersonTypeId = 2,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000019"),
                            Alias = "amartin",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1987, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Andrew",
                            GenderId = 1,
                            LastName = "Martin",
                            MiddleName = "S",
                            PersonTypeId = 3,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Alias = "slee",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Stephanie",
                            GenderId = 2,
                            LastName = "Lee",
                            MiddleName = "T",
                            PersonTypeId = 4,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000021"),
                            Alias = "kthompson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1984, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Kevin",
                            GenderId = 1,
                            LastName = "Thompson",
                            MiddleName = "U",
                            PersonTypeId = 1,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000022"),
                            Alias = "nwhite",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Nicole",
                            GenderId = 2,
                            LastName = "White",
                            MiddleName = "V",
                            PersonTypeId = 2,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000023"),
                            Alias = "bharris",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1986, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Brian",
                            GenderId = 1,
                            LastName = "Harris",
                            MiddleName = "W",
                            PersonTypeId = 3,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000024"),
                            Alias = "rclark",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Rachel",
                            GenderId = 2,
                            LastName = "Clark",
                            MiddleName = "X",
                            PersonTypeId = 4,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000025"),
                            Alias = "slewis",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1983, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Steven",
                            GenderId = 1,
                            LastName = "Lewis",
                            MiddleName = "Y",
                            PersonTypeId = 1,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000026"),
                            Alias = "mrobinson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Melissa",
                            GenderId = 2,
                            LastName = "Robinson",
                            MiddleName = "Z",
                            PersonTypeId = 2,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000027"),
                            Alias = "twalker",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Timothy",
                            GenderId = 1,
                            LastName = "Walker",
                            MiddleName = "AA",
                            PersonTypeId = 3,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000028"),
                            Alias = "kyoung",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Kimberly",
                            GenderId = 2,
                            LastName = "Young",
                            MiddleName = "AB",
                            PersonTypeId = 4,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000029"),
                            Alias = "rallen",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Richard",
                            GenderId = 1,
                            LastName = "Allen",
                            MiddleName = "AC",
                            PersonTypeId = 1,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000030"),
                            Alias = "lking",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Laura",
                            GenderId = 2,
                            LastName = "King",
                            MiddleName = "AD",
                            PersonTypeId = 2,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000031"),
                            Alias = "cwright",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1987, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Charles",
                            GenderId = 1,
                            LastName = "Wright",
                            MiddleName = "AE",
                            PersonTypeId = 3,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000032"),
                            Alias = "hscott",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Heather",
                            GenderId = 2,
                            LastName = "Scott",
                            MiddleName = "AF",
                            PersonTypeId = 4,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000033"),
                            Alias = "jgreen",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1984, 9, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Joseph",
                            GenderId = 1,
                            LastName = "Green",
                            MiddleName = "AG",
                            PersonTypeId = 1,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000034"),
                            Alias = "ebaker",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Elizabeth",
                            GenderId = 2,
                            LastName = "Baker",
                            MiddleName = "AH",
                            PersonTypeId = 2,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000035"),
                            Alias = "tadams",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1986, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Thomas",
                            GenderId = 1,
                            LastName = "Adams",
                            MiddleName = "AI",
                            PersonTypeId = 3,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000036"),
                            Alias = "cnelson",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Christine",
                            GenderId = 2,
                            LastName = "Nelson",
                            MiddleName = "AJ",
                            PersonTypeId = 4,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000037"),
                            Alias = "pcarter",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Paul",
                            GenderId = 1,
                            LastName = "Carter",
                            MiddleName = "AK",
                            PersonTypeId = 1,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000038"),
                            Alias = "smitchell",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Samantha",
                            GenderId = 2,
                            LastName = "Mitchell",
                            MiddleName = "AL",
                            PersonTypeId = 2,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000039"),
                            Alias = "mperez",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1987, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Mark",
                            GenderId = 1,
                            LastName = "Perez",
                            MiddleName = "AM",
                            PersonTypeId = 3,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000040"),
                            Alias = "proberts",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Patricia",
                            GenderId = 2,
                            LastName = "Roberts",
                            MiddleName = "AN",
                            PersonTypeId = 4,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000041"),
                            Alias = "dturner",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Donald",
                            GenderId = 1,
                            LastName = "Turner",
                            MiddleName = "AO",
                            PersonTypeId = 1,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000042"),
                            Alias = "nphillips",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1991, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Nancy",
                            GenderId = 2,
                            LastName = "Phillips",
                            MiddleName = "AP",
                            PersonTypeId = 2,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000043"),
                            Alias = "gcampbell",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1986, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "George",
                            GenderId = 1,
                            LastName = "Campbell",
                            MiddleName = "AQ",
                            PersonTypeId = 3,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000044"),
                            Alias = "kparker",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1993, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Karen",
                            GenderId = 2,
                            LastName = "Parker",
                            MiddleName = "AR",
                            PersonTypeId = 4,
                            RaceId = 2
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000045"),
                            Alias = "eevans",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1984, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Edward",
                            GenderId = 1,
                            LastName = "Evans",
                            MiddleName = "AS",
                            PersonTypeId = 1,
                            RaceId = 3
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000046"),
                            Alias = "bedwards",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Betty",
                            GenderId = 2,
                            LastName = "Edwards",
                            MiddleName = "AT",
                            PersonTypeId = 2,
                            RaceId = 4
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000047"),
                            Alias = "wcollins",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1987, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "William",
                            GenderId = 1,
                            LastName = "Collins",
                            MiddleName = "AU",
                            PersonTypeId = 3,
                            RaceId = 5
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000048"),
                            Alias = "hstewart",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Helen",
                            GenderId = 2,
                            LastName = "Stewart",
                            MiddleName = "AV",
                            PersonTypeId = 4,
                            RaceId = 6
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000049"),
                            Alias = "rsanchez",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Ronald",
                            GenderId = 1,
                            LastName = "Sanchez",
                            MiddleName = "AW",
                            PersonTypeId = 1,
                            RaceId = 1
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000050"),
                            Alias = "mmorris",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnteredBy = "System",
                            FirstName = "Margaret",
                            GenderId = 3,
                            LastName = "Morris",
                            MiddleName = "AX",
                            PersonTypeId = 2,
                            RaceId = 2
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.PersonType", b =>
                {
                    b.Property<int>("PersonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonTypeId"));

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ClientOption")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("PersonTypeId");

                    b.HasIndex("ClientId");

                    b.ToTable("PersonTypes");

                    b.HasData(
                        new
                        {
                            PersonTypeId = 1,
                            ClientOption = false,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Employee",
                            EnteredBy = "System",
                            Name = "Employee"
                        },
                        new
                        {
                            PersonTypeId = 2,
                            ClientOption = false,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Contractor",
                            EnteredBy = "System",
                            Name = "Contractor"
                        },
                        new
                        {
                            PersonTypeId = 3,
                            ClientOption = false,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer",
                            EnteredBy = "System",
                            Name = "Customer"
                        },
                        new
                        {
                            PersonTypeId = 4,
                            ClientOption = false,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vendor",
                            EnteredBy = "System",
                            Name = "Vendor"
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Phone", b =>
                {
                    b.Property<Guid>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("PhoneTypeId")
                        .HasColumnType("integer");

                    b.HasKey("PhoneId");

                    b.HasIndex("PhoneTypeId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.PhoneType", b =>
                {
                    b.Property<int>("PhoneTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhoneTypeId"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<bool>("ClientOption")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("PhoneTypeId");

                    b.ToTable("PhoneTypes");

                    b.HasData(
                        new
                        {
                            PhoneTypeId = 1,
                            ClientOption = false,
                            Description = "Home phone number",
                            Name = "Home"
                        },
                        new
                        {
                            PhoneTypeId = 2,
                            ClientOption = false,
                            Description = "Work phone number",
                            Name = "Work"
                        },
                        new
                        {
                            PhoneTypeId = 3,
                            ClientOption = false,
                            Description = "Mobile phone number",
                            Name = "Mobile"
                        },
                        new
                        {
                            PhoneTypeId = 4,
                            ClientOption = false,
                            Description = "Fax number",
                            Name = "Fax"
                        },
                        new
                        {
                            PhoneTypeId = 5,
                            ClientOption = false,
                            Description = "Emergency contact number",
                            Name = "Emergency"
                        });
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "White",
                            EnteredBy = "System",
                            Name = "White"
                        },
                        new
                        {
                            RaceId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Black or African American",
                            EnteredBy = "System",
                            Name = "Black or African American"
                        },
                        new
                        {
                            RaceId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asian",
                            EnteredBy = "System",
                            Name = "Asian"
                        },
                        new
                        {
                            RaceId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Native American or Alaska Native",
                            EnteredBy = "System",
                            Name = "Native American"
                        },
                        new
                        {
                            RaceId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Native Hawaiian or Other Pacific Islander",
                            EnteredBy = "System",
                            Name = "Pacific Islander"
                        },
                        new
                        {
                            RaceId = 6,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Other/Unspecified",
                            EnteredBy = "System",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Address", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.AddressType", null)
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Client", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.ClientType", null)
                        .WithMany()
                        .HasForeignKey("ClientTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Person", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaggiesPlaygroundApi.Models.PersonType", "PersonType")
                        .WithMany()
                        .HasForeignKey("PersonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaggiesPlaygroundApi.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("PersonType");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.PersonType", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MaggiesPlaygroundApi.Models.Phone", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.PhoneType", null)
                        .WithMany()
                        .HasForeignKey("PhoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaggiesPlaygroundApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MaggiesPlaygroundApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
